### ISSUE TITLE
'OpenJDK 64-Bit Server VM' version 21+ Not Working?

### ISSUE THREAD

**Issue by Ploofis** [Gaming32/additive-installer#6] opened 2024-05-19 22:56 UTC
Hello! I've been trying to run additive/adrenaline on Minecraft Java version 1.20.6, and every time I try to it says that 'OpenJDK 64-Bit Server VM' needs to be updated to 21 or newer.
If I run "java -version" in command prompt to check what version Java is on, it says that OpenJDK is on version 22.0.1, and also says that it is on 'OpenJDK 64-Bit Server VM 22.0.1'. My OpenJDK 64-Bit Server VM is not on version 17, nothing seems to be connected to version 17, and so I'm unsure of why this won't work, and even more unsure of why it says it is on version 17.
If I try to load additive/adrenaline on 1.20.4 (or a previous version) it works perfectly fine, not a single issue or concern, but it won't run properly on 1.20.6. It says that other mods are 'incompatable' because of it (supposedly) being on OpenJDK 64-Bit Server VM version 17.
I have put the error code I get when I try to open Minecraft Java below (it crashes every time before getting to the loading screen) in case there's something in there that might be the issue, but I'm really not sure what the problem is.
My java is on 22.0.1 and 'OpenJDK 64-Bit Server VM' is on version 22.0.1 as well. I also had a friend try to install additive and they had the same issue as me.
If there is a solution to this issue, please let me know. I've tried reinstalling additive and adrenaline, I've tried updating some of the mods, and nothing has worked so far. Let me know if you have any questions, thank you in advance <3

Both error codes are below, they're basically the same:

Error code for additive:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'OpenJDK 64-Bit Server VM' (java) 17 with version 21 or later.
More details:
	 - Mod 'Fabric API' (fabric-api) 0.98.0+1.20.6 requires version 21 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 17!
	 - Mod 'Capes' (capes) 1.5.4+1.20.5 requires version 21 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 17!
	 - Mod 'ImmediatelyFast' (immediatelyfast) 1.2.14+1.20.6 requires version 21 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 17!
	 - Mod 'Main Menu Credits' (isxander-main-menu-credits) 1.2.0 requires version 21 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 17!
	 - Mod 'More Culling' (moreculling) 0.25.0 requires version 21 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 17!
	 - Mod 'OptiGUI' (optigui) 2.3.0-beta.2+1.20.5 requires version 21 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 17!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Error code for adrenaline:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
     
Replace 'OpenJDK 64-Bit Server VM' (java) 17 with version 21 or later.
More details:
     
Mod 'Fabric API' (fabric-api) 0.98.0+1.20.6 requires version 21 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 17!
Mod 'ImmediatelyFast' (immediatelyfast) 1.2.14+1.20.6 requires version 21 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 17!
Mod 'More Culling' (moreculling) 0.25.0 requires version 21 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 17!
at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Gaming32** [comment] 2024-05-19 22:56
Duplicate of #4.

**Closed as not planned by Gaming32** 2024-05-19 22:56 UTC
